title: Will Pink
description: Adventures in Containers, Cloud and everything in between
url: https://mrpink.github.io
author: Will Pink

markdown: kramdown
theme: null

plugins:
  - jekyll-feed

# SEO defaults
defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/og-default.png
